defmodule Ankole.Company.OrganizationalUnit do
  @moduledoc """
  Durable Organizational Unit within a Company.

  A Unit is a Company-scoped node in an acyclic hierarchy. Each Unit has a
  stable identity, a mutable name, a lifecycle state, and an optional parent
  Unit. Units do not carry Principal relationships, roles, or metadata.

  The `uid` field is a caller-supplied stable identity. The internal `id`
  is an autogenerated UUIDv7.
  """

  use Ecto.Schema

  import Ecto.Changeset
  import Ankole.Ecto.Changeset, only: [normalize_blank: 2]

  alias Ankole.Company
  alias Ankole.Company.OrganizationalUnit

  @primary_key {:id, Ankole.Ecto.UUIDv7, autogenerate: true}
  @timestamps_opts [type: :utc_datetime_usec]

  schema "organizational_units" do
    field :uid, :string
    field :name, :string
    field :status, Ecto.Enum, values: [:active, :archived], default: :active

    belongs_to :company, Company,
      foreign_key: :company_uid,
      references: :uid,
      type: :string

    belongs_to :parent_unit, OrganizationalUnit,
      foreign_key: :parent_unit_uid,
      references: :uid,
      type: :string

    timestamps()
  end

  @doc """
  Builds a changeset for organizational unit rows.
  """
  @spec changeset(struct(), map()) :: Ecto.Changeset.t()
  def changeset(unit, attrs) do
    unit
    |> cast(attrs, [:uid, :name, :status, :company_uid, :parent_unit_uid])
    |> normalize_blank([:name])
    |> validate_required([:uid, :name, :company_uid])
    |> validate_uid_nonblank()
    |> unique_constraint(:uid, name: :organizational_units_uid_index)
    |> check_constraint(:uid, name: :organizational_units_uid_present)
    |> check_constraint(:name, name: :organizational_units_name_present)
    |> foreign_key_constraint(:company_uid)
    |> foreign_key_constraint(:parent_unit_uid)
  end

  defp validate_uid_nonblank(changeset) do
    case get_field(changeset, :uid) do
      uid when is_binary(uid) ->
        if String.trim(uid) != "" do
          changeset
        else
          add_error(changeset, :uid, "uid must not be blank")
        end

      _ ->
        add_error(changeset, :uid, "uid must not be blank")
    end
  end
end
